(cl:in-package mavros_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          AVAILABLE_INFO-VAL
          AVAILABLE_INFO
          SYSID-VAL
          SYSID
          COMPID-VAL
          COMPID
          AUTOPILOT-VAL
          AUTOPILOT
          TYPE-VAL
          TYPE
          SYSTEM_STATUS-VAL
          SYSTEM_STATUS
          BASE_MODE-VAL
          BASE_MODE
          CUSTOM_MODE-VAL
          CUSTOM_MODE
          MODE-VAL
          MODE
          MODE_ID-VAL
          MODE_ID
          CAPABILITIES-VAL
          CAPABILITIES
          FLIGHT_SW_VERSION-VAL
          FLIGHT_SW_VERSION
          MIDDLEWARE_SW_VERSION-VAL
          MIDDLEWARE_SW_VERSION
          OS_SW_VERSION-VAL
          OS_SW_VERSION
          BOARD_VERSION-VAL
          BOARD_VERSION
          FLIGHT_CUSTOM_VERSION-VAL
          FLIGHT_CUSTOM_VERSION
          VENDOR_ID-VAL
          VENDOR_ID
          PRODUCT_ID-VAL
          PRODUCT_ID
          UID-VAL
          UID
))