(cl:in-package mavros_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIME_LAST_BASELINE_MS-VAL
          TIME_LAST_BASELINE_MS
          RTK_RECEIVER_ID-VAL
          RTK_RECEIVER_ID
          WN-VAL
          WN
          TOW-VAL
          TOW
          RTK_HEALTH-VAL
          RTK_HEALTH
          RTK_RATE-VAL
          RTK_RATE
          NSATS-VAL
          NSATS
          BASELINE_COORDS_TYPE-VAL
          BASELINE_COORDS_TYPE
          BASELINE_A_MM-VAL
          BASELINE_A_MM
          BASELINE_B_MM-VAL
          BASELINE_B_MM
          BASELINE_C_MM-VAL
          BASELINE_C_MM
          ACCURACY-VAL
          ACCURACY
          IAR_NUM_HYPOTHESES-VAL
          IAR_NUM_HYPOTHESES
))