(cl:in-package mavros_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          FIX_TYPE-VAL
          FIX_TYPE
          LAT-VAL
          LAT
          LON-VAL
          LON
          ALT-VAL
          ALT
          EPH-VAL
          EPH
          EPV-VAL
          EPV
          VEL-VAL
          VEL
          COG-VAL
          COG
          SATELLITES_VISIBLE-VAL
          SATELLITES_VISIBLE
          ALT_ELLIPSOID-VAL
          ALT_ELLIPSOID
          H_ACC-VAL
          H_ACC
          V_ACC-VAL
          V_ACC
          VEL_ACC-VAL
          VEL_ACC
          HDG_ACC-VAL
          HDG_ACC
          DGPS_NUMCH-VAL
          DGPS_NUMCH
          DGPS_AGE-VAL
          DGPS_AGE
))