(cl:in-package mavros_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ICAO_ADDRESS-VAL
          ICAO_ADDRESS
          CALLSIGN-VAL
          CALLSIGN
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          HEADING-VAL
          HEADING
          HOR_VELOCITY-VAL
          HOR_VELOCITY
          VER_VELOCITY-VAL
          VER_VELOCITY
          ALTITUDE_TYPE-VAL
          ALTITUDE_TYPE
          EMITTER_TYPE-VAL
          EMITTER_TYPE
          TSLC-VAL
          TSLC
          FLAGS-VAL
          FLAGS
          SQUAWK-VAL
          SQUAWK
))