(cl:in-package mavros_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          COMPONENT-VAL
          COMPONENT
          UPTIME-VAL
          UPTIME
          TYPE-VAL
          TYPE
          CPU_CORES-VAL
          CPU_CORES
          CPU_COMBINED-VAL
          CPU_COMBINED
          GPU_CORES-VAL
          GPU_CORES
          GPU_COMBINED-VAL
          GPU_COMBINED
          TEMPERATURE_BOARD-VAL
          TEMPERATURE_BOARD
          TEMPERATURE_CORE-VAL
          TEMPERATURE_CORE
          FAN_SPEED-VAL
          FAN_SPEED
          RAM_USAGE-VAL
          RAM_USAGE
          RAM_TOTAL-VAL
          RAM_TOTAL
          STORAGE_TYPE-VAL
          STORAGE_TYPE
          STORAGE_USAGE-VAL
          STORAGE_USAGE
          STORAGE_TOTAL-VAL
          STORAGE_TOTAL
          LINK_TYPE-VAL
          LINK_TYPE
          LINK_TX_RATE-VAL
          LINK_TX_RATE
          LINK_RX_RATE-VAL
          LINK_RX_RATE
          LINK_TX_MAX-VAL
          LINK_TX_MAX
          LINK_RX_MAX-VAL
          LINK_RX_MAX
))