(cl:in-package mavros_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ATTITUDE_STATUS_FLAG-VAL
          ATTITUDE_STATUS_FLAG
          VELOCITY_HORIZ_STATUS_FLAG-VAL
          VELOCITY_HORIZ_STATUS_FLAG
          VELOCITY_VERT_STATUS_FLAG-VAL
          VELOCITY_VERT_STATUS_FLAG
          POS_HORIZ_REL_STATUS_FLAG-VAL
          POS_HORIZ_REL_STATUS_FLAG
          POS_HORIZ_ABS_STATUS_FLAG-VAL
          POS_HORIZ_ABS_STATUS_FLAG
          POS_VERT_ABS_STATUS_FLAG-VAL
          POS_VERT_ABS_STATUS_FLAG
          POS_VERT_AGL_STATUS_FLAG-VAL
          POS_VERT_AGL_STATUS_FLAG
          CONST_POS_MODE_STATUS_FLAG-VAL
          CONST_POS_MODE_STATUS_FLAG
          PRED_POS_HORIZ_REL_STATUS_FLAG-VAL
          PRED_POS_HORIZ_REL_STATUS_FLAG
          PRED_POS_HORIZ_ABS_STATUS_FLAG-VAL
          PRED_POS_HORIZ_ABS_STATUS_FLAG
          GPS_GLITCH_STATUS_FLAG-VAL
          GPS_GLITCH_STATUS_FLAG
          ACCEL_ERROR_STATUS_FLAG-VAL
          ACCEL_ERROR_STATUS_FLAG
))