// Generated by gencpp from file mavros_msgs/CommandHome.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_COMMANDHOME_H
#define MAVROS_MSGS_MESSAGE_COMMANDHOME_H

#include <ros/service_traits.h>


#include <mavros_msgs/CommandHomeRequest.h>
#include <mavros_msgs/CommandHomeResponse.h>


namespace mavros_msgs
{

struct CommandHome
{

typedef CommandHomeRequest Request;
typedef CommandHomeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommandHome
} // namespace mavros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros_msgs::CommandHome > {
  static const char* value()
  {
    return "05b5da557a6a0cf6c2b958dba173bca1";
  }

  static const char* value(const ::mavros_msgs::CommandHome&) { return value(); }
};

template<>
struct DataType< ::mavros_msgs::CommandHome > {
  static const char* value()
  {
    return "mavros_msgs/CommandHome";
  }

  static const char* value(const ::mavros_msgs::CommandHome&) { return value(); }
};


// service_traits::MD5Sum< ::mavros_msgs::CommandHomeRequest> should match
// service_traits::MD5Sum< ::mavros_msgs::CommandHome >
template<>
struct MD5Sum< ::mavros_msgs::CommandHomeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::CommandHome >::value();
  }
  static const char* value(const ::mavros_msgs::CommandHomeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::CommandHomeRequest> should match
// service_traits::DataType< ::mavros_msgs::CommandHome >
template<>
struct DataType< ::mavros_msgs::CommandHomeRequest>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::CommandHome >::value();
  }
  static const char* value(const ::mavros_msgs::CommandHomeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros_msgs::CommandHomeResponse> should match
// service_traits::MD5Sum< ::mavros_msgs::CommandHome >
template<>
struct MD5Sum< ::mavros_msgs::CommandHomeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::CommandHome >::value();
  }
  static const char* value(const ::mavros_msgs::CommandHomeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::CommandHomeResponse> should match
// service_traits::DataType< ::mavros_msgs::CommandHome >
template<>
struct DataType< ::mavros_msgs::CommandHomeResponse>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::CommandHome >::value();
  }
  static const char* value(const ::mavros_msgs::CommandHomeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_COMMANDHOME_H
