// Generated by gencpp from file mavros_msgs/CommandInt.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_COMMANDINT_H
#define MAVROS_MSGS_MESSAGE_COMMANDINT_H

#include <ros/service_traits.h>


#include <mavros_msgs/CommandIntRequest.h>
#include <mavros_msgs/CommandIntResponse.h>


namespace mavros_msgs
{

struct CommandInt
{

typedef CommandIntRequest Request;
typedef CommandIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommandInt
} // namespace mavros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros_msgs::CommandInt > {
  static const char* value()
  {
    return "5d5fd287bf3d27ad6ec508b1692f3b09";
  }

  static const char* value(const ::mavros_msgs::CommandInt&) { return value(); }
};

template<>
struct DataType< ::mavros_msgs::CommandInt > {
  static const char* value()
  {
    return "mavros_msgs/CommandInt";
  }

  static const char* value(const ::mavros_msgs::CommandInt&) { return value(); }
};


// service_traits::MD5Sum< ::mavros_msgs::CommandIntRequest> should match
// service_traits::MD5Sum< ::mavros_msgs::CommandInt >
template<>
struct MD5Sum< ::mavros_msgs::CommandIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::CommandInt >::value();
  }
  static const char* value(const ::mavros_msgs::CommandIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::CommandIntRequest> should match
// service_traits::DataType< ::mavros_msgs::CommandInt >
template<>
struct DataType< ::mavros_msgs::CommandIntRequest>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::CommandInt >::value();
  }
  static const char* value(const ::mavros_msgs::CommandIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros_msgs::CommandIntResponse> should match
// service_traits::MD5Sum< ::mavros_msgs::CommandInt >
template<>
struct MD5Sum< ::mavros_msgs::CommandIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::CommandInt >::value();
  }
  static const char* value(const ::mavros_msgs::CommandIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::CommandIntResponse> should match
// service_traits::DataType< ::mavros_msgs::CommandInt >
template<>
struct DataType< ::mavros_msgs::CommandIntResponse>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::CommandInt >::value();
  }
  static const char* value(const ::mavros_msgs::CommandIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_COMMANDINT_H
