// Generated by gencpp from file mavros_msgs/FileRemove.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_FILEREMOVE_H
#define MAVROS_MSGS_MESSAGE_FILEREMOVE_H

#include <ros/service_traits.h>


#include <mavros_msgs/FileRemoveRequest.h>
#include <mavros_msgs/FileRemoveResponse.h>


namespace mavros_msgs
{

struct FileRemove
{

typedef FileRemoveRequest Request;
typedef FileRemoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FileRemove
} // namespace mavros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros_msgs::FileRemove > {
  static const char* value()
  {
    return "1c309002d7f7c6df7d3f094925ea8e10";
  }

  static const char* value(const ::mavros_msgs::FileRemove&) { return value(); }
};

template<>
struct DataType< ::mavros_msgs::FileRemove > {
  static const char* value()
  {
    return "mavros_msgs/FileRemove";
  }

  static const char* value(const ::mavros_msgs::FileRemove&) { return value(); }
};


// service_traits::MD5Sum< ::mavros_msgs::FileRemoveRequest> should match
// service_traits::MD5Sum< ::mavros_msgs::FileRemove >
template<>
struct MD5Sum< ::mavros_msgs::FileRemoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::FileRemove >::value();
  }
  static const char* value(const ::mavros_msgs::FileRemoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::FileRemoveRequest> should match
// service_traits::DataType< ::mavros_msgs::FileRemove >
template<>
struct DataType< ::mavros_msgs::FileRemoveRequest>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::FileRemove >::value();
  }
  static const char* value(const ::mavros_msgs::FileRemoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros_msgs::FileRemoveResponse> should match
// service_traits::MD5Sum< ::mavros_msgs::FileRemove >
template<>
struct MD5Sum< ::mavros_msgs::FileRemoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::FileRemove >::value();
  }
  static const char* value(const ::mavros_msgs::FileRemoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::FileRemoveResponse> should match
// service_traits::DataType< ::mavros_msgs::FileRemove >
template<>
struct DataType< ::mavros_msgs::FileRemoveResponse>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::FileRemove >::value();
  }
  static const char* value(const ::mavros_msgs::FileRemoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_FILEREMOVE_H
