// Generated by gencpp from file mavros_msgs/FileChecksumResponse.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_FILECHECKSUMRESPONSE_H
#define MAVROS_MSGS_MESSAGE_FILECHECKSUMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavros_msgs
{
template <class ContainerAllocator>
struct FileChecksumResponse_
{
  typedef FileChecksumResponse_<ContainerAllocator> Type;

  FileChecksumResponse_()
    : crc32(0)
    , success(false)
    , r_errno(0)  {
    }
  FileChecksumResponse_(const ContainerAllocator& _alloc)
    : crc32(0)
    , success(false)
    , r_errno(0)  {
  (void)_alloc;
    }



   typedef uint32_t _crc32_type;
  _crc32_type crc32;

   typedef uint8_t _success_type;
  _success_type success;

   typedef int32_t _r_errno_type;
  _r_errno_type r_errno;





  typedef boost::shared_ptr< ::mavros_msgs::FileChecksumResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::FileChecksumResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FileChecksumResponse_

typedef ::mavros_msgs::FileChecksumResponse_<std::allocator<void> > FileChecksumResponse;

typedef boost::shared_ptr< ::mavros_msgs::FileChecksumResponse > FileChecksumResponsePtr;
typedef boost::shared_ptr< ::mavros_msgs::FileChecksumResponse const> FileChecksumResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::FileChecksumResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::FileChecksumResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavros_msgs::FileChecksumResponse_<ContainerAllocator1> & lhs, const ::mavros_msgs::FileChecksumResponse_<ContainerAllocator2> & rhs)
{
  return lhs.crc32 == rhs.crc32 &&
    lhs.success == rhs.success &&
    lhs.r_errno == rhs.r_errno;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavros_msgs::FileChecksumResponse_<ContainerAllocator1> & lhs, const ::mavros_msgs::FileChecksumResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::FileChecksumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::FileChecksumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::FileChecksumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::FileChecksumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::FileChecksumResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::FileChecksumResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::FileChecksumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ecf737b97670b745ca39c7b185cc756";
  }

  static const char* value(const ::mavros_msgs::FileChecksumResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ecf737b97670b74ULL;
  static const uint64_t static_value2 = 0x5ca39c7b185cc756ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::FileChecksumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/FileChecksumResponse";
  }

  static const char* value(const ::mavros_msgs::FileChecksumResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::FileChecksumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 crc32\n"
"bool success\n"
"int32 r_errno\n"
"\n"
;
  }

  static const char* value(const ::mavros_msgs::FileChecksumResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::FileChecksumResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.crc32);
      stream.next(m.success);
      stream.next(m.r_errno);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FileChecksumResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::FileChecksumResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::FileChecksumResponse_<ContainerAllocator>& v)
  {
    s << indent << "crc32: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.crc32);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "r_errno: ";
    Printer<int32_t>::stream(s, indent + "  ", v.r_errno);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_FILECHECKSUMRESPONSE_H
