// Generated by gencpp from file mavros_msgs/FileRename.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_FILERENAME_H
#define MAVROS_MSGS_MESSAGE_FILERENAME_H

#include <ros/service_traits.h>


#include <mavros_msgs/FileRenameRequest.h>
#include <mavros_msgs/FileRenameResponse.h>


namespace mavros_msgs
{

struct FileRename
{

typedef FileRenameRequest Request;
typedef FileRenameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FileRename
} // namespace mavros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros_msgs::FileRename > {
  static const char* value()
  {
    return "07d853e3d48c88a648998515aab1f5b7";
  }

  static const char* value(const ::mavros_msgs::FileRename&) { return value(); }
};

template<>
struct DataType< ::mavros_msgs::FileRename > {
  static const char* value()
  {
    return "mavros_msgs/FileRename";
  }

  static const char* value(const ::mavros_msgs::FileRename&) { return value(); }
};


// service_traits::MD5Sum< ::mavros_msgs::FileRenameRequest> should match
// service_traits::MD5Sum< ::mavros_msgs::FileRename >
template<>
struct MD5Sum< ::mavros_msgs::FileRenameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::FileRename >::value();
  }
  static const char* value(const ::mavros_msgs::FileRenameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::FileRenameRequest> should match
// service_traits::DataType< ::mavros_msgs::FileRename >
template<>
struct DataType< ::mavros_msgs::FileRenameRequest>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::FileRename >::value();
  }
  static const char* value(const ::mavros_msgs::FileRenameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros_msgs::FileRenameResponse> should match
// service_traits::MD5Sum< ::mavros_msgs::FileRename >
template<>
struct MD5Sum< ::mavros_msgs::FileRenameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::FileRename >::value();
  }
  static const char* value(const ::mavros_msgs::FileRenameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::FileRenameResponse> should match
// service_traits::DataType< ::mavros_msgs::FileRename >
template<>
struct DataType< ::mavros_msgs::FileRenameResponse>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::FileRename >::value();
  }
  static const char* value(const ::mavros_msgs::FileRenameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_FILERENAME_H
