// Generated by gencpp from file mavros_msgs/FileChecksum.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_FILECHECKSUM_H
#define MAVROS_MSGS_MESSAGE_FILECHECKSUM_H

#include <ros/service_traits.h>


#include <mavros_msgs/FileChecksumRequest.h>
#include <mavros_msgs/FileChecksumResponse.h>


namespace mavros_msgs
{

struct FileChecksum
{

typedef FileChecksumRequest Request;
typedef FileChecksumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FileChecksum
} // namespace mavros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros_msgs::FileChecksum > {
  static const char* value()
  {
    return "c32158e17d9a1a1c682fe19adbd29fac";
  }

  static const char* value(const ::mavros_msgs::FileChecksum&) { return value(); }
};

template<>
struct DataType< ::mavros_msgs::FileChecksum > {
  static const char* value()
  {
    return "mavros_msgs/FileChecksum";
  }

  static const char* value(const ::mavros_msgs::FileChecksum&) { return value(); }
};


// service_traits::MD5Sum< ::mavros_msgs::FileChecksumRequest> should match
// service_traits::MD5Sum< ::mavros_msgs::FileChecksum >
template<>
struct MD5Sum< ::mavros_msgs::FileChecksumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::FileChecksum >::value();
  }
  static const char* value(const ::mavros_msgs::FileChecksumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::FileChecksumRequest> should match
// service_traits::DataType< ::mavros_msgs::FileChecksum >
template<>
struct DataType< ::mavros_msgs::FileChecksumRequest>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::FileChecksum >::value();
  }
  static const char* value(const ::mavros_msgs::FileChecksumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros_msgs::FileChecksumResponse> should match
// service_traits::MD5Sum< ::mavros_msgs::FileChecksum >
template<>
struct MD5Sum< ::mavros_msgs::FileChecksumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::FileChecksum >::value();
  }
  static const char* value(const ::mavros_msgs::FileChecksumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::FileChecksumResponse> should match
// service_traits::DataType< ::mavros_msgs::FileChecksum >
template<>
struct DataType< ::mavros_msgs::FileChecksumResponse>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::FileChecksum >::value();
  }
  static const char* value(const ::mavros_msgs::FileChecksumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_FILECHECKSUM_H
