// Generated by gencpp from file mavros_msgs/LogRequestData.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_LOGREQUESTDATA_H
#define MAVROS_MSGS_MESSAGE_LOGREQUESTDATA_H

#include <ros/service_traits.h>


#include <mavros_msgs/LogRequestDataRequest.h>
#include <mavros_msgs/LogRequestDataResponse.h>


namespace mavros_msgs
{

struct LogRequestData
{

typedef LogRequestDataRequest Request;
typedef LogRequestDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LogRequestData
} // namespace mavros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros_msgs::LogRequestData > {
  static const char* value()
  {
    return "91170669bcd08438f0440f9b4d12a11a";
  }

  static const char* value(const ::mavros_msgs::LogRequestData&) { return value(); }
};

template<>
struct DataType< ::mavros_msgs::LogRequestData > {
  static const char* value()
  {
    return "mavros_msgs/LogRequestData";
  }

  static const char* value(const ::mavros_msgs::LogRequestData&) { return value(); }
};


// service_traits::MD5Sum< ::mavros_msgs::LogRequestDataRequest> should match
// service_traits::MD5Sum< ::mavros_msgs::LogRequestData >
template<>
struct MD5Sum< ::mavros_msgs::LogRequestDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::LogRequestData >::value();
  }
  static const char* value(const ::mavros_msgs::LogRequestDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::LogRequestDataRequest> should match
// service_traits::DataType< ::mavros_msgs::LogRequestData >
template<>
struct DataType< ::mavros_msgs::LogRequestDataRequest>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::LogRequestData >::value();
  }
  static const char* value(const ::mavros_msgs::LogRequestDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros_msgs::LogRequestDataResponse> should match
// service_traits::MD5Sum< ::mavros_msgs::LogRequestData >
template<>
struct MD5Sum< ::mavros_msgs::LogRequestDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::LogRequestData >::value();
  }
  static const char* value(const ::mavros_msgs::LogRequestDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::LogRequestDataResponse> should match
// service_traits::DataType< ::mavros_msgs::LogRequestData >
template<>
struct DataType< ::mavros_msgs::LogRequestDataResponse>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::LogRequestData >::value();
  }
  static const char* value(const ::mavros_msgs::LogRequestDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_LOGREQUESTDATA_H
