// Generated by gencpp from file mavros_msgs/LogRequestList.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_LOGREQUESTLIST_H
#define MAVROS_MSGS_MESSAGE_LOGREQUESTLIST_H

#include <ros/service_traits.h>


#include <mavros_msgs/LogRequestListRequest.h>
#include <mavros_msgs/LogRequestListResponse.h>


namespace mavros_msgs
{

struct LogRequestList
{

typedef LogRequestListRequest Request;
typedef LogRequestListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LogRequestList
} // namespace mavros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros_msgs::LogRequestList > {
  static const char* value()
  {
    return "3e2e88c935b3047e14f450bc4a90c4d2";
  }

  static const char* value(const ::mavros_msgs::LogRequestList&) { return value(); }
};

template<>
struct DataType< ::mavros_msgs::LogRequestList > {
  static const char* value()
  {
    return "mavros_msgs/LogRequestList";
  }

  static const char* value(const ::mavros_msgs::LogRequestList&) { return value(); }
};


// service_traits::MD5Sum< ::mavros_msgs::LogRequestListRequest> should match
// service_traits::MD5Sum< ::mavros_msgs::LogRequestList >
template<>
struct MD5Sum< ::mavros_msgs::LogRequestListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::LogRequestList >::value();
  }
  static const char* value(const ::mavros_msgs::LogRequestListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::LogRequestListRequest> should match
// service_traits::DataType< ::mavros_msgs::LogRequestList >
template<>
struct DataType< ::mavros_msgs::LogRequestListRequest>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::LogRequestList >::value();
  }
  static const char* value(const ::mavros_msgs::LogRequestListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros_msgs::LogRequestListResponse> should match
// service_traits::MD5Sum< ::mavros_msgs::LogRequestList >
template<>
struct MD5Sum< ::mavros_msgs::LogRequestListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::LogRequestList >::value();
  }
  static const char* value(const ::mavros_msgs::LogRequestListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::LogRequestListResponse> should match
// service_traits::DataType< ::mavros_msgs::LogRequestList >
template<>
struct DataType< ::mavros_msgs::LogRequestListResponse>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::LogRequestList >::value();
  }
  static const char* value(const ::mavros_msgs::LogRequestListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_LOGREQUESTLIST_H
